spring.datasource.url=jdbc:postgresql://localhost:5432/smart_healthcare
spring.datasource.username=postgres
spring.datasource.password=smarthealth123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=MySuperSecretKeyForSmartHealthcareSystem2026MySuperSecretKey
jwt.expiration=86400000

tesseract.data.path=/usr/share/tesseract-ocr/5/tessdata

# Multipart upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB